"""
Find waitlist-request emails in the UIMakerLab Emails app.

Matches the "Waitlist Request: <Camp> — <Session>" subject generated by the
website's Join Waitlist mailto links, plus any free-form email mentioning
"waitlist". Compiles sender, camp/session (parsed from subject when present),
date, and a short body preview. Does NOT fetch comments (fast, no rate-limit
risk). Output: waitlist_requests.json + console summary.
"""

import json
import re
from datetime import datetime
from podio_client import get_client

EMAIL_APP_ID = 12703942
# Scan back to when summer-2026 registration opened.
SINCE = datetime(2026, 1, 1)


def get_field_value(item, external_id):
    for field in item.get("fields", []):
        if field.get("external_id") == external_id:
            values = field.get("values", [])
            if values:
                val = values[0].get("value", "")
                if isinstance(val, dict):
                    return val.get("text", val.get("name", str(val)))
                return str(val)
    return ""


def parse_camp_session(subject):
    """Pull camp + session from 'Waitlist Request: <Camp> — <Session>'."""
    m = re.search(r"waitlist\s+request\s*:\s*(.+)", subject, re.I)
    if not m:
        return None, None
    rest = m.group(1).strip()
    # Split on em-dash / en-dash / hyphen separating camp and session
    parts = re.split(r"\s+[—–-]\s+", rest, maxsplit=1)
    camp = parts[0].strip()
    session = parts[1].strip() if len(parts) > 1 else None
    return camp, session


def main():
    client = get_client()
    print("Authenticated. Scanning UIMakerLab Emails for waitlist requests...\n")

    matches = []
    offset = 0
    batch = 30
    scanned = 0
    done = False

    while not done:
        result = client.post(f"/item/app/{EMAIL_APP_ID}/filter/", {
            "limit": batch, "offset": offset,
            "sort_by": "created_on", "sort_desc": True,
        })
        items = result.get("items", [])
        total = result.get("total", 0)
        if offset == 0:
            print(f"Total emails in app: {total}\n")
        if not items:
            break

        for item in items:
            created = item.get("created_on", "")
            try:
                created_dt = datetime.strptime(created, "%Y-%m-%d %H:%M:%S")
            except (ValueError, TypeError):
                continue
            if created_dt < SINCE:
                done = True
                break
            scanned += 1

            subject = get_field_value(item, "title")
            body = get_field_value(item, "body")
            sender = get_field_value(item, "from")
            status = get_field_value(item, "status")

            text = re.sub(r"<[^>]+>", " ", subject + " " + body).lower()
            if "waitlist" not in text and "wait list" not in text:
                continue

            camp, session = parse_camp_session(subject)
            body_text = re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", body)).strip()
            matches.append({
                "item_id": item.get("item_id"),
                "from": sender,
                "subject": subject,
                "camp": camp,
                "session": session,
                "status": status,
                "created": created,
                "body_preview": body_text[:400],
                "podio_url": f"https://podio.com/illinois-makerlab/lab-operations/apps/uimakerlab-emails/items/{item.get('item_id')}",
            })

        if not done:
            offset += batch
            if offset >= total:
                break

    matches.sort(key=lambda m: m["created"])
    print(f"Scanned {scanned} emails since {SINCE.date()}; "
          f"found {len(matches)} waitlist-related.\n")
    print("=" * 70)
    for i, m in enumerate(matches, 1):
        print(f"{i}. {m['created']}  from: {m['from']}")
        print(f"   Subject: {m['subject']}")
        if m["camp"]:
            print(f"   → Camp: {m['camp']}  | Session: {m['session']}")
        print(f"   Body: {m['body_preview'][:180]}")
        print()

    with open("waitlist_requests.json", "w") as f:
        json.dump(matches, f, indent=2)
    print("Saved to waitlist_requests.json")


if __name__ == "__main__":
    main()
